# Misc
set -g mouse on
set -g base-index 1
set -s escape-time 0
setw -g aggressive-resize on
set-option -g status-position top 

# Set custom prefix and reload
set -g prefix M-a
unbind-key C-b
bind-key M-a send-prefix
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Status bar
set -g status-bg black
set -g status-fg blue

# Vim keybindings
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind p paste-buffer
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip"

# Defaults
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"
set-option -g default-shell /usr/bin/fish
